# Juan Pedro Puig - 281088
# Pedro Azambuja - 270218

services:
  app:
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: so
      MONGO_INITDB_ROOT_PASSWORD: so
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo: